// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/27/2025, 7:26:17 AM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/rafi/Documents/project/test-katekima/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/plugins/**/*.{js,ts,mjs}","/Users/rafi/Documents/project/test-katekima/stores/**/*.{js,ts,mjs}","/Users/rafi/Documents/project/test-katekima/composables/**/*.{js,ts,mjs}","/Users/rafi/Documents/project/test-katekima/utils/**/*.{js,ts,mjs}","/Users/rafi/Documents/project/test-katekima/pages/index.vue","/Users/rafi/Documents/project/test-katekima/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rafi/Documents/project/test-katekima/app.config.{js,ts,mjs}","/Users/rafi/Documents/project/test-katekima/app/spa-loading-template.html"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;